[package]
name = "rafy"
version = "0.1.0"
authors = ["Ritiek <ritiekmalhotra123@gmail.com>"]

[dependencies]
hyper = "0.10.8"
hyper-native-tls = "0.2.2"
pbr = "1.0.0-alpha.3"
regex = "0.2.1"
serde_json = "1.0"
